---
title: "Intro to Formal Political Analysis:\\newline Extensive Games of Perfect Information"
author: "JBrandon Duck-Mayr"
date: "`r quack::american_date_format(Sys.Date())`"
urlcolor: Blue
header-includes:
    - \newcommand{\setsep}{\setlength{\itemsep}{3pt}}
    - \newcommand{\setskip}{\setlength{\parskip}{3pt}}
    - \renewcommand{\tightlist}{\setsep\setskip}
    - \setlength{\abovedisplayskip}{-6pt}
    - \newcommand{\pd}[1]{\ensuremath{\frac{\partial}{\partial{#1}}}}
    - \newcommand{\gray}{\color{white}}
    - \usepackage{tikz}
    - \usetikzlibrary{backgrounds, calc}
    # From https://tex.stackexchange.com/a/416169/140224
    - \usepackage{multirow}
    - \newcommand{\STAB}[1]{\begin{tabular}{@{}c@{}}#1\end{tabular}}
output:
    quack::presentation:
        toc: false
        incremental: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Introducing... TIME

\only<2-7>{
\begin{tabular}{p{12mm}llcc}
& & & \multicolumn{2}{c}{Incumbent} \\[0.5em]
& & & Acquiesce & Fight \\[0.25em]
& \multirow{2}{*}{Challenger}
& In  & \textcolor<7>{BurntOrange}{\textbf<5->{2}, \textbf<3->{1}} & 0, 0 \\
& & Out & 1, \textbf<4->{2} & \textcolor<7>{BurntOrange}{\textbf<6->{1}, \textbf<4->{2}}
\end{tabular}
}

\only<8-10>{
\begin{figure}
\centering
\begin{tikzpicture}
    %% Set the "styles" as described above
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = black]
    \tikzstyle{hollow node}=[circle, draw, inner sep = 1.5]
    %% You can even use styles to specify how far apart nodes should be
    \tikzstyle{level 1}=[level distance = 20mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 20mm, sibling distance = 3cm]
    %% This is the root node
    \node (0) [hollow node, label = above:{Challenger}] {}
        %% This is the first (left-most) child node
        child{ node (1) [solid node, label = above left:{Incumbent}] {}
            %% It has its own children
            child{ node {\textbf<10->{2}, \textbf<9->{1}} edge from parent node [left] {$Acquiesce$} }
            child{ node {0, 0} edge from parent node [right] {$Fight$} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {$In$}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node {1, 2} edge from parent node [above right] {$Out$} }
        ;
\end{tikzpicture}
\end{figure}
}

\only<11>{
\begin{figure}
\centering
\begin{tikzpicture}[
        emph/.style={edge from parent/.style={BurntOrange, very thick, draw}},
        norm/.style={edge from parent/.style={black, thin, draw}}
    ]
    %% Set the "styles" as described above
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = BurntOrange, color = BurntOrange]
    \tikzstyle{hollow node}=[circle, draw, thick, inner sep = 1.5, color = BurntOrange]
    %% You can even use styles to specify how far apart nodes should be
    \tikzstyle{level 1}=[level distance = 20mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 20mm, sibling distance = 3cm]
    %% This is the root node
    \node (0) [hollow node, label = above:{Challenger}] {}
        %% This is the first (left-most) child node
        child[emph]{ node (1) [solid node, label = above left:{Incumbent}] {}
            %% It has its own children
            child[emph] { node {\textcolor{BurntOrange}{\textbf{2}, \textbf{1}}} edge from parent node [left] {$Acquiesce$} }
            child[norm] { node {0, 0} edge from parent node [right] {$Fight$} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {$In$}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node {1, 2} edge from parent node [above right] {$Out$} }
        ;
\end{tikzpicture}
\end{figure}
}

## Extensive form games of perfect information

::: {.block}
### Osborne Definition 155.1
An **extensive game with perfect information** consists of

- a set of **players**
- a set of sequences (**terminal histories**) with the property that no sequence is a proper subhistory of some terminal history
- a function (the **player function**) that assigns a player to every sequence that is a proper subhistory of some terminal history
- for each player, **preferences** over the set of terminal histories
:::

. . .

- A history is just a sequence (in order) of actions taken by players
- A terminal history is a history that is not a proper subhistory of any other history

## Extensive form games of perfect information

Osborne Example 155.2: Entry game

- Players
  + The challenger and the incumbent
- Terminal histories
  + $(In, Acquiesce)$, $(In, Fight)$, and $Out$
- Player function
  + $P(\varnothing) = Challenger$ and $P(In) = Incumbent$
- Preferences
  + The challenger's preferences are represented by the payoff function $u_1(In, Acquiesce) = 2, u_1(Out) = 1$, and $u_1(In, Fight) = 0$
  + The incumbent's preferences are represented by the payoff function $u_2(Out) = 2, u_2(In, Acquiesce) = 1$, and $u_2(In, Fight) = 0$

## Differences in definitions or notation

- Some list the elements of extensive games differently
- e.g., notice **actions** are not listed in Osborne's definition
  + actions inferred from the player function & terminal histories
  + but some textbooks/treatments list actions separately
- Some textbooks/treatments have a narrower definition of **perfect information** than Osborne
  + Osborne: perfect information = when choosing an action, players always know everything that's happened previously + players always move alone
  + Tadelis: Osborne's requirements + no moves by Nature
- We're going to cover all games where players always know everything that happened previously when they move

## Game tree representation

\begin{figure}
\centering
\begin{tikzpicture}
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = black]
    \tikzstyle{hollow node}=[circle, draw, inner sep = 1.5]
    \tikzstyle{level 1}=[level distance = 20mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 20mm, sibling distance = 3cm]
    %% This is the root node
    \node (0) [hollow node, label = above:{Challenger}] {}
        %% This is the first (left-most) child node
        child{ node (1) [solid node, label = above left:{Incumbent}] {}
            %% It has its own children
            child{ node {2, 1} edge from parent node [left] {$Acquiesce$} }
            child{ node {0, 0} edge from parent node [right] {$Fight$} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {$In$}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node {1, 2} edge from parent node [above right] {$Out$} }
        ;
\end{tikzpicture}
\end{figure}

## Strategies in extensive form games

::: {.block}
### Osborne Definition 159.1
A **strategy** of player $i$ in an extensive game with perfect information is a function that assigns to each history $h$ after which it is player $i$'s turn to move (i.e. $P(h) = i$, where $P$ is the player function) an action in $A(h)$ (the set of actions available after $h$).
:::

. . .

That is, it's a "plan of action" for every situation $i$ could find themselves in

## Strategies in extensive form games

Example (Osborne Figure 159.1)

\begin{figure}
\centering
\begin{tikzpicture}
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = black]
    \tikzstyle{hollow node}=[circle, draw, inner sep = 1.5]
    \tikzstyle{level 1}=[level distance = 10mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 10mm, sibling distance = 3cm]
    %% This is the root node
    \node (0) [hollow node, label = above:{1}] {}
        %% This is the first (left-most) child node
        child{ node (1) [solid node, label = above left:{2}] {}
            %% It has its own children
            child{ node {2, 1} edge from parent node [above left] {$E$} }
            child{ node {3, 0} edge from parent node [above right] {$F$} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {$C$}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node (2) [solid node, label = above right:{2}] {}
            %% It has its own children
            child{ node {0, 2} edge from parent node [above left] {$G$} }
            child{ node {1, 3} edge from parent node [above right] {$H$} }
            %% This specifies the edge from node (2) to node (0)
            edge from parent node [above right] {$D$}
        }
        ;
\end{tikzpicture}
\end{figure}

. . .

\begin{table}
\centering
\begin{tabular}{lcc}
& Action assigned to $h = C$ & Action assigned to $h = D$ \\
Strategy 1 & $E$ & $G$ \\
Strategy 2 & $E$ & $H$ \\
Strategy 3 & $F$ & $G$ \\
Strategy 4 & $F$ & $H$ \\
\end{tabular}
\end{table}

. . .

&nbsp;

Player 2's possible strategies: $EG$, $EH$, $FG$, $FH$

## Normal form representation

\only<1>{
\begin{figure}
\centering
\begin{tikzpicture}
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = black]
    \tikzstyle{hollow node}=[circle, draw, inner sep = 1.5]
    \tikzstyle{level 1}=[level distance = 20mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 20mm, sibling distance = 3cm]
    %% This is the root node
    \node (0) [hollow node, label = above:{Challenger}] {}
        %% This is the first (left-most) child node
        child{ node (1) [solid node, label = above left:{Incumbent}] {}
            %% It has its own children
            child{ node {2, 1} edge from parent node [left] {$Acquiesce$} }
            child{ node {0, 0} edge from parent node [right] {$Fight$} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {$In$}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node {1, 2} edge from parent node [above right] {$Out$} }
        ;
\end{tikzpicture}
\end{figure}
}

\only<2>{
\begin{tabular}{p{12mm}llcc}
& & & \multicolumn{2}{c}{Incumbent} \\[0.5em]
& & & Acquiesce & Fight \\[0.25em]
& \multirow{2}{*}{Challenger}
& In  & 2, 1 & 0, 0 \\
& & Out & 1, 2 & 1, 2
\end{tabular}
}

## Subgames

::: {.block .nonincremental}
### Osborne Definition 164.1
Let $\Gamma$ be an extensive game with perfect information, with player function $P$. For any nonterminal history $h$ of $\Gamma$, the **subgame** $\Gamma(h)$ **following the history** $h$ is the following extensive game:

- Players: The players in $\Gamma$
- Terminal histories: The set of all sequences $h'$ of actions such that $(h, h')$ is a terminal history of $\Gamma$
- Player function: The player $P(h, h')$ is assigned to each proper subhistory of a terminal history
- Preferences: Each player prefers $h'$ to $h''$ if and only if they prefer $(h, h')$ to $(h, h'')$ in $\Gamma$
:::

## Subgames

\begin{figure}
\centering
\begin{tikzpicture}
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = black]
    \tikzstyle{hollow node}=[circle, draw, inner sep = 1.5]
    \tikzstyle{level 1}=[level distance = 20mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 20mm, sibling distance = 3cm]
    %% This is the root node
    \node (a) [hollow node, label = above:{1}] {}
        %% This is the first (left-most) child node
        child{ node (b) [solid node, label = above left:{2}] {}
            %% It has its own children
            child{ node {2, 1} edge from parent node [above left] {$E$} }
            child{ node {3, 0} edge from parent node [above right] {$F$} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {$C$}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node (c) [solid node, label = above right:{2}] {}
            %% It has its own children
            child{ node {0, 2} edge from parent node [above left] {$G$} }
            child{ node {1, 3} edge from parent node [above right] {$H$} }
            %% This specifies the edge from node (2) to node (0)
            edge from parent node [above right] {$D$}
        }
        ;
    \onslide<2->{
    \draw [dashed] (b) + (0, -1) ellipse (2.25 and 2);
    }
    \onslide<3->{
    \draw [dashed] (c) + (0, -1) ellipse (2.25 and 2);
    }
    \onslide<4->{
    \draw [dashed] (a) + (0, -2.5) ellipse (5.25 and 3.5);
    }
\end{tikzpicture}
\end{figure}

## Sequential rationality

Given strategies $s_{-i}$ of the players other than $i$,
player $i$'s strategy $s_i$ is **sequentially rational**
if and only if $i$ is playing a best response to $s_{-i}$
at every history $h$ after which it is player $i$'s turn to move
(i.e. $P(h) = i$).

## Subgame perfection

::: {.block}
### Osborne definition 166.1
The strategy profile $s^\ast$ in an extensive game with perfect information is a **subgame perfect equilibrium** if, for every player $i$, every history $h$ after which it is player $i$'s turn to move (i.e. $P(h) = i$), and every strategy $r_i$ of player $i$, the terminal history $O_h\left(s^\ast\right)$ generated by $s^\ast$ after the history $h$ is at least as good according to player $i$'s preferences as the terminal history $O_h\left(r_i, s^\ast_{-i}\right)$...

&nbsp;

Equivalently, for every player $i$ and every history $h$ after which it is player $i$'s turn to move, $$ u_i\left(O_h\left(s^\ast\right)\right) \geq u_i\left(O_h\left(r_i, s^\ast_{-i}\right)\right) \text{ for every strategy } r_i \text{ of player } i $$
:::

## Subgame perfection

\begin{figure}
\centering
\begin{tikzpicture}[
        emph/.style={edge from parent/.style={BurntOrange, very thick, draw}},
        norm/.style={edge from parent/.style={black, thin, draw}}
    ]
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = BurntOrange, color = BurntOrange]
    \tikzstyle{hollow node}=[circle, draw, thick, inner sep = 1.5, color = BurntOrange]
    \tikzstyle{level 1}=[level distance = 10mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 20mm, sibling distance = 3cm]
    %% This is the root node
    \node (0) [hollow node, label = above:{Challenger}] {}
        %% This is the first (left-most) child node
        child[emph] { node (1) [solid node, label = above left:{Incumbent}] {}
            %% It has its own children
            child[emph] { node {\textcolor{BurntOrange}{\textbf{2, 1}}} edge from parent node [above left] {$Acquiesce$} }
            child[norm] { node {0, 0} edge from parent node [above right] {$Fight$} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {$In$}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node {1, 2} edge from parent node [above right] {$Out$} }
        ;
\end{tikzpicture}
\end{figure}

&nbsp;

\begin{tabular}{p{12mm}llcc}
& & & \multicolumn{2}{c}{Incumbent} \\[0.5em]
& & & Acquiesce & Fight \\[0.25em]
& \multirow{2}{*}{Challenger}
& In  & \textcolor{BurntOrange}{\textbf{2, 1}} & 0, 0 \\
& & Out & 1, 2 & \textcolor{BurntOrange}{\textbf{1, 2}}
\end{tabular}

## Backward induction

. . .

- Find the optimal actions of the players who move in all subgames of length 1
- Taking those actions as given, find the optimal actions of the players who move in all subgames of length 2
- Continue working back to the beginning of the game

## Example: Centipede Game

\begin{figure}
\centering
\begin{tikzpicture}[font=\footnotesize,scale=1]
% Two node styles: solid and hollow
\tikzstyle{solid node}=[circle,draw,inner sep=1.2,fill=black];
\tikzstyle{hollow node}=[circle,draw,inner sep=1.2];
% The Tree
\node(0)[hollow node]{}
child[grow=down]{node[solid node]{}edge from parent node[left]{$S$}}
child[grow=right]{node(1)[solid node]{}
child[grow=down]{node[solid node]{}edge from parent node[left]{$S$}}
child[grow=right]{node(2)[solid node]{}
child[grow=down]{node[solid node]{}edge from parent node[left]{$S$}}
child[grow=right]{node(3)[solid node]{}
child[grow=down]{node[solid node]{}edge from parent node[left]{$S$}}
child[grow=right]{node(4)[solid node]{}
child[grow=down]{node[solid node]{}edge from parent node[left]{$S$}}
child[grow=right]{node(5)[solid node]{}
child[grow=down]{node[solid node]{}edge from parent node[left]{$S$}}
child[grow=right]{node(6)[solid node]{}
edge from parent node[above]{$C$}
}
edge from parent node[above]{$C$}
}
edge from parent node[above]{$C$}
}
edge from parent node[above]{$C$}
}
edge from parent node[above]{$C$}
}
edge from parent node[above]{$C$}
};
% Movers
\foreach \x in {0,2,4}
\node[above]at(\x){1};
\foreach \x in {1,3,5}
\node[above]at(\x){2};
% payoffs
\node[below]at(0-1){$1,0$};
\node[below]at(1-1){$0,2$};
\node[below]at(2-1){$3,1$};
\node[below]at(3-1){$2,4$};
\node[below]at(4-1){$5,3$};
\node[below]at(5-1){$4,6$};
\node[right]at(6){$6,5$};
\end{tikzpicture}
\end{figure}

## Finiteness

- If the length of the longest terminal history is finite, the game has a **finite horizon**
- If a game has a finite horizon *and* finitely many terminal histories, it is **finite**

. . .

::: {.block}
### Zermelo's Theorem
Any finite game of perfect information has a backward induction solution that is sequentially rational. If no two terminal histories prescribe the same payoff to any player then the solution is unique.
:::

. . .

::: {.block}
### Stigler's Law
No scientific discovery is named after it's original discoverer.
:::

. . .

Stigler's law was originally discovered by Robert K. Merton.

## Examples

. . .

- Ultimatum game
- Mutually assured destruction
- Hotelling-Downs with strategic voters
- Committee decision making
- Agenda-setting with moves by chance

## Mutually Assured Destruction

\begin{figure}
\centering
\begin{tikzpicture}
    \tikzstyle{solid node}=[circle,  draw, inner sep = 1.5, fill = black]
    \tikzstyle{hollow node}=[circle, draw, inner sep = 1.5]
    \tikzstyle{level 1}=[level distance = 20mm, sibling distance = 5cm]
    \tikzstyle{level 2}=[level distance = 30mm, sibling distance = 5cm]
    %% This is the root node
    \node (a) [hollow node, label = above:{USA}] {}
        %% This is the first (left-most) child node
        child{ node (b) [solid node, label = above left:{USSR}] {}
            %% It has its own children
            child{ node {
                \begin{tabular}{clcc}
                & & \multicolumn{2}{c}{USSR} \\
                \multirow{3}{*}{\STAB{\rotatebox[origin=c]{90}{USA}}}
                & & R & D \\
                & R & -5, -5 & -100, -100 \\
                & D & -100, -100 & -100, -100
                \end{tabular}
                }
                edge from parent node [above left] {Confront}
            }
            child{ node {10, -10} edge from parent node [above right] {Back Down} }
            %% This specifies the edge from node (1) to node (0)
            edge from parent node [above left] {Escalate}
        }
        %% This is the right-most child node of the root node, or node (0)
        child{ node {0, 0} edge from parent node [above right] {Ignore} }
        ;
\end{tikzpicture}
\end{figure}
