---
title: "Intro to Formal Political Analysis:\\newline Dynamic Games of Incomplete Information"
author: "JBrandon Duck-Mayr"
date: "`r quack::american_date_format(Sys.Date())`"
urlcolor: Blue
header-includes:
    - \newcommand{\setsep}{\setlength{\itemsep}{3pt}}
    - \newcommand{\setskip}{\setlength{\parskip}{3pt}}
    - \renewcommand{\tightlist}{\setsep\setskip}
    - \setlength{\abovedisplayskip}{-6pt}
    - \usepackage{tikz}
    - \usetikzlibrary{arrows, calc, positioning}
output:
    quack::presentation:
        toc: false
        incremental: true
---

## Accounting for both time and uncertainty

Consider the following scenario:

- Pat's game theory professor is old-timey and requires hard-copy problem set submissions
- A p-set is due, but Pat must rush to another class for an exam
- Pat notices Terry, a student they have never met; suppose
  + A proportion $p$ of students are nice and prefer to help people
  + But $1-p$ of students are jerks
  + And Pat doesn't know which type Terry is
- Pat has two options:
  + Turn in the problem set late for a penalty\invisible<1-8>{, or}
  + Ask Terry to hand it to the prof while Pat rushes to the exam
- If Pat asks for help, Terry can either deliver the p-set or not

\textcolor{gray}{\tiny (Example adapted from Tadelis exercise 15.3)}

## Accounting for both time and uncertainty

\begin{figure}
\centering
\begin{tikzpicture}[font=\footnotesize]
\draw (0,2) -- (0,-2);
\node at (0,0) {$\bullet$};
\node[right] at (0,0) {Chance};
\node[right] at (0,1) {Nice with $p$};
\node[right] at (0,-1) {Jerk with $1-p$};
\draw (-3,2) -- (3,2);
\draw (-3,-2) -- (3,-2);
\node at (0,2) {$\bullet$};
\node at (0,-2) {$\bullet$};
\draw[dashed] (0,2) to[ out=225, in=135] (0,-2);
\node[left] at (-1,0) {Pat};
\node[above] at (-1.5,2) {$S$};
\node[above] at (1.5,2) {$L$};
\node[below] at (-1.5,-2) {$S$};
\node[below] at (1.5,-2) {$L$};
\node at (-3,2) {$\bullet$};
\node at (-3,-2) {$\bullet$};
\node[right] at (3,2) {0,0};
\node[right] at (3,-2) {0,0};
\node[below] at (-2.5,2) {Terry};
\node[above] at (-2.5,-2) {Terry};
\draw (-4,1)-- (-3,2) -- (-4,3);
\draw (-4,-1)-- (-3,-2) -- (-4,-3);
\node[left] at (-3.5, 2.5) {$D$};
\node[left] at (-3.5, 1.5) {$T$};
\node[left] at (-3.5, -2.5) {$T$};
\node[left] at (-3.5, -1.5) {$D$};
\node[left] at (-4,3) {1,1};
\node[left] at (-4,1) {-1,0};
\node[left] at (-4,-3) {-1,1};
\node[left] at (-4,-1) {1,0};
% \node[above] at (0,2) {$\mu$};
% \node[below] at (0,-2) {$1-\mu$};
\end{tikzpicture}
\end{figure}

## Accounting for both time and uncertainty

- Modeling this as a Bayesian game eliminates the possibility of a second-mover advantage for Terry
- But we also can't model it the same way we modeled extensive form games before because there's a move by Chance *before* Pat's move
- So we need some more tools

## Information sets

First we need a way to talk about players not knowing what "node" of a game tree they're at

. . .

::: {.block}
### Information sets (adapted from Tadelis Definition 7.2)
Every player $i$ has a collection of **information sets** $I_i \in H_i$ that partition the nodes of the game at which player $i$ moves with the following properties:

&nbsp;

1. If $I_i$ is a singleton that includes only $h$ then player $i$ who moves at $h$ knows they are at $h$.
2. If $h \neq h'$ and if both $h \in I_i$ and $h' \in I_i$ then player $i$ who moves at $h$ does not know whether they are at $h$ or $h'$.
3. If $h \in I_i$ and $h' \in I_i$ then $A_i\left(h\right) = A_i\left(h'\right)$.
:::

## Strategies

::: {.block}
### Osborne Definition 318.1
A (pure) strategy of player $i$ in an extensive game is a function that assigns to each of $i$'s information sets $I_i$ an action in $A\left(I_i\right)$ (the set of actions available to player $i$ at information set $I_i$)
:::

. . .

::: {.block}
### Osborne Definition 324.2
A **behavioral strategy** of player $i$ in an extensive game is a function that assigns to each of $i$'s information sets $I_i$ a probability distribution over the actions in $A\left(I_i\right)$, with the property that each probability distribution is independent of every other distribution.
:::

## Belief systems

::: {.block}
### Osborne Definition 324.1
A **belief system**  in an extensive game is a function that assigns to each information set a probability distribution over the histories in that information set.
:::

## Assessments

::: {.block}
### Osborne Definition 325.1
An **assessment** in an extensive game is a pair consisting of a profile of behavioral strategies and a belief system.
:::

## Perfect Bayesian Equilibrium

::: {.block}
### Osborne Definition 328.1 (lightly edited)
An assessment $(\beta, \mu)$ (consisting of a behavioral strategy profile $\beta$ and a belief system $\mu$) is a **weak sequential equilibrium** if it satisfies the following two conditions:

. . .

&nbsp;

1. **Sequential rationality**: Each player's strategy is optimal in the part of the game that follows each of their information sets, given the strategy profile and their belief about the history in the information set that has occurred...
2. **Weak consistency**: for every information set $I_i$ reached with positive probability given the strategy profile $\beta$, the probability assigned by the belief system to each history $h^\ast \in I_i$ is given by [Bayes' rule].
:::

## Back to Pat and Terry

\begin{figure}
\centering
\begin{tikzpicture}[font=\footnotesize]
\draw (0,2) -- (0,-2);
\node at (0,0) {$\bullet$};
\node[right] at (0,0) {Chance};
\node[right] at (0,1) {Nice with $p$};
\node[right] at (0,-1) {Jerk with $1-p$};
\draw (-3,2) -- (3,2);
\draw (-3,-2) -- (3,-2);
\node at (0,2) {$\bullet$};
\node at (0,-2) {$\bullet$};
\draw[dashed] (0,2) to[ out=225, in=135] (0,-2);
\node[left] at (-1,0) {Pat};
\node[above] at (-1.5,2) {$S$};
\node[above] at (1.5,2) {$L$};
\node[below] at (-1.5,-2) {$S$};
\node[below] at (1.5,-2) {$L$};
\node at (-3,2) {$\bullet$};
\node at (-3,-2) {$\bullet$};
\node[right] at (3,2) {0,0};
\node[right] at (3,-2) {0,0};
\node[below] at (-2.5,2) {Terry};
\node[above] at (-2.5,-2) {Terry};
\draw (-4,1)-- (-3,2) -- (-4,3);
\draw (-4,-1)-- (-3,-2) -- (-4,-3);
\node[left] at (-3.5, 2.5) {$D$};
\node[left] at (-3.5, 1.5) {$T$};
\node[left] at (-3.5, -2.5) {$T$};
\node[left] at (-3.5, -1.5) {$D$};
\node[left] at (-4,3) {1,1};
\node[left] at (-4,1) {-1,0};
\node[left] at (-4,-3) {-1,1};
\node[left] at (-4,-1) {1,0};
\onslide<2>{\node[above] at (0,2) {$\mu$};}
\onslide<2>{\node[below] at (0,-2) {$1-\mu$};}
\end{tikzpicture}
\end{figure}

## The Gift Game

\begin{figure}
    \small
 	\begin{center}
    \begin{tikzpicture}[thin,every circle node/.style={minimum size=1.5mm,inner sep=0mm}]
		\tikzstyle{level 1}=[level distance=1.5in]
		\tikzstyle{level 2}=[level distance=.75in]
		\tikzstyle{level 3}=[level distance=.75in, sibling distance=30mm]		
        \node[circle,draw,label={above:Chance}] (root) {}
        		child[grow=left] {node[circle,fill,label=left:1]{}
        				child[grow=up] {node(1)[above]{$0,0$}
        					edge from parent
        					node[left]{$No$ $Gift$}}
        				child[grow=down] {node(3)[circle,fill]{}
        						child {node[below]{$1,1$}
        							edge from parent
        							node[above left]{$[a]$ $A$}}
        						child {node[below]{$-1,0$}
        							edge from parent
        							node[above right]{$R$}}
        					edge from parent
        					node[left]{$[f]$ $Gift$}}
        			edge from parent
        			node[above]{$p$}
        			node[below]{$Friend$}}
        		child[grow=right] {node[circle,fill,label=right:1]{}
        				child[grow=up] {node[above]{$0,0$}
        					edge from parent
        					node[right]{$No$ $Gift$}}
        				child[grow=down] {node(4)[circle,fill]{}
        						child {node[below]{$1,-1$}
        							edge from parent
        							node[above left]{$A$}}
        						child {node[below]{$-1,0$}
        							edge from parent
        							node[above right]{$R$}}
        					edge from parent
        					node[right]{$Gift$ $[e]$}}
        			edge from parent
        			node[above]{$1-p$}
        			node[below]{$Enemy$}};
		\draw[dashed](3)to(4);
		\node[above] at($(3)!.5!(4)$){2};
		\node[left = 1mm of 3] {$\mu$};
    \end{tikzpicture}
    \end{center}
\end{figure}

## The Gift Game

Let's find the pure strategy PBE.

. . .

First note there cannot be an equilibrium where Friends give gifts and Enemies don't; for the Friend type to give a gift, it must be that player 2 chooses $A$, but if that were true, Enemy types would always give gifts also.

. . .

It is trivial to show that the strategy profile $(NN, R)$ paired with any belief system is a PBE.

. . .

Additionally, $(GG, A)$ with $\mu = p$ is a PBE when $p \geq 0.5$.

## The Gift Game

Now let's consider mixed-strategy PBE.
When can both types give gifts with the same probability? i.e., when can $0 < f = e < 1$?

. . .

What about where $0 \leq f < e \leq 1$ or $0 \leq e < f \leq 1$?

## The Gift Game

If $f > 0$ or $e > 0$, $\mu$ is constrained by consistency, so $\mu$ must be $\frac{pf}{pf + e(1 - p)}$.

. . .

If $f$ or $e$ are also less than one, it must be that $EU_1(G) = EU_1(N) = 0$, which means $a$ must be $0.5$.

## The Gift Game

If $a = 0.5$, it must be that $EU_2(A) = EU_2(R)$, so it must also be that \pause $\frac{p}{1 - p} = \frac{e}{f}$:

. . .

\begin{align*}
    2\mu - 1                    & = 0 \\
    2\mu                        & = 1 \\
    \mu                         & = 0.5 \\
    \frac{pf}{pf + e(1 - p)}    & = 0.5 \\[0.5em]
    \frac{2pf}{pf + e(1 - p)}   & = 1 \\[0.5em]
    2pf                         & = pf + e (1 - p) \\
    pf                          & = e (1 - p) \\[0.5em]
    \frac{p}{1 - p}             & = \frac{e}{f}
\end{align*}

## The Gift Game

So, there can be mixed strategy PBE iff

. . .

$$
f, e > 0, 0 < p \leq \frac{1}{2}, a = \frac{1}{2}, \text{ and } \frac{p}{1 - p} = \frac{e}{f}.
$$

. . .

In this PBE, note that both types of Player 1 have the same strategy if and only if $p = 0.5$; the strategy differs based on type otherwise.
