---
title: "GOV 385N Problem Set 6"
author: "Instructor: JBrandon Duck-Mayr"
fontsize: 12pt
header-includes:
    - \usepackage{multirow}
    - \newcommand{\setsep}{\setlength{\itemsep}{1pt}}
    - \newcommand{\setskip}{\setlength{\parskip}{1pt}}
    - \renewcommand{\tightlist}{\setsep\setskip}
output: quack::article
---

# Armed Conflict (Tadelis 12.3)

Consider the following strategic situation:
Two rival armies plan to seize a disputed territory.
Each army's general can choose either to attack ($A$) or not ($N$).
In addition, each army is either strong ($S$) or weak ($W$) with equal probability, and the realizations for each army are *independent*.
Furthermore, the type of each army is known only to that army's general.
An army can capture the territory if either
(i) it attacks and its rival does not or
(ii) it and its rival attack, but it is strong and the rival is weak.
If both attack and are of equal strength, then neither captures the territory.
As for payoffs, the territory is worth $m$ if captured and each army has a cost of fighting equal to $s$ if it is strong and $w$ if it is weak, where $s < w$.
If an army attacks but its rival does not, no costs are borne by either side.
Identify all the pure strategy Bayesian Nash equilibria of this game for the following two cases, and briefly describe the intuition for your results:

a. $m = 3, w = 2, s = 1$
b. $m = 3, w = 4, s = 2$

# Trading Places (Tadelis 12.7)

Two players, 1 and 2, each own a house.
Each player $i$ values their own house at $v_i$.
The value of player $i$'s house to the other player is $\frac{3}{2}v_i$.
Each player $i$ knows the value $v_i$ of their own house to themselves, but not the value of the other player's house.
The values $v_i$ are drawn independently from the interval $[0, 1]$ with uniform distribution.

a. Suppose players announce simultaneously whether they want to exchange their houses.
   If both players agree to an exchange, then the exchange takes place.
   Find a Bayesian Nash equilibrium of this game in pure strategies in which player $i$ accepts an exchange if and only if the value $v_i$ does not exceed some threshold $\theta_i$.
b. How would your answer to (a) change if player $j$'s valuation of player $i$'s house were $\frac{5}{2}v_i$?
c. Try to explain why any Bayesian Nash equilibrium of the game described in (a) must involve threshold strategies of the type postulated in (a).

\clearpage

# Jury Voting[^1]

Consider a more general version of the jury voting game introduced in lecture.

- There are $n$ jurors ($n$ odd) who must choose to convict or acquit
- There is an unknown state of the world $\omega \in \{G,I\}$ (guilty or innocent). The jurors' common prior is $\Pr\left( \omega = I \right) = \pi \in (0,1)$.
- Each juror independently receives a signal $\theta_i \in \{0, 1\}$; for all jurors $$ \Pr\left( \theta_i = 1 \mid \omega = G \right) = \Pr\left( \theta_i = 0 \mid \omega = I \right) = p > 0 $$ (i.e. if we say $\theta_i = 1$ signals guilt, each signal is correct with probability $p$)
- After observing the signal, the jurors simultaneously cast votes $a_i \in \{c, a\}$ (convict or acquit)
- The outcome $x \in \{C, A\}$ is determined by a $q$-majority voting rule: $x = C$ if & only if at least $q$ jurors choose $a_i = c$, where $\frac{n+1}{2} \leq q \leq n$ (i.e. from simple majority rule to unanimity); otherwise the defendant is acquitted.
- All jurors' preferences are given as follows: $u(A, I) = u(C, G) = 0$, $u(C, I) = -\pi$, and $u(A, G) = -(1 - \pi)$ where $\pi \in (0, 1)$

Characterize the Bayesian Nash equilibrium of this game as a function of $n$, $q$ and $p$. Discuss the effects of the number of jurors, the voting rule, and the accuracy of signals.

[^1]: I believe this problem was originally written by Keith Schnakenberg (I lightly edited it).
